version: "3.8"
services:

  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"

    environment:
      - GRID_MAX_SESSION= 16
      - GRID_BROWSER_TIMEOUT= 2000
      - GRID_TIMEOUT= 3000

  chrome:
    image: selenium/node-chrome:3.141.59
    container_name: web-automation_chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"